<?php

use App\Http\Controllers\SuperAdminController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\UserManageController;
use App\Http\Controllers\AdministrationController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\BasicController;
use App\Http\Controllers\MenuController;
use App\Http\Controllers\EventController;
use App\Http\Controllers\SlideController;
use App\Http\Controllers\DepartmentController;
use App\Http\Controllers\NavbarController;
use App\Http\Controllers\MessageController;
use App\Http\Controllers\PrincipalController;
use App\Http\Controllers\PrincipaldetailsController;
use App\Http\Controllers\ViceprincipalController;
use App\Http\Controllers\VicepdetailsController;
use App\Http\Controllers\AcademinCouncilController;
use App\Http\Controllers\TeacherCouncilController;
use App\Http\Controllers\HeadofdepartmentController;
use App\Http\Controllers\QucklinksController;
use App\Http\Controllers\BreakingNewsController;
use App\Http\Controllers\SubmenuController;
use App\Http\Controllers\TeacherController;
use App\Http\Controllers\TeacherCouncilHBController;
use App\Http\Controllers\StaffController;
use App\Http\Controllers\ExprincipalController;
use App\Http\Controllers\NoticeBoardController;
use App\Http\Controllers\NOCController;
use App\Http\Controllers\OfficeOrderController;
use App\Http\Controllers\LibraryCardController;
use App\Http\Controllers\LibrarianController;
use App\Http\Controllers\InstrucionController;
use App\Http\Controllers\BookIssueController;
use App\Http\Controllers\BookstockController;
use App\Http\Controllers\BookRefundController;
use App\Http\Controllers\SportsTeacherController;
use App\Http\Controllers\ChampionController;
use App\Http\Controllers\SNoticeController;
use App\Http\Controllers\ArtsdepartmentController;
use App\Http\Controllers\ExViceprincipalController;
use App\Http\Controllers\AnnualCommitteesController;
use App\Http\Controllers\ArtsdepartmentHistoryController;
use App\Http\Controllers\DepartmentmanageController;
use App\Http\Controllers\college_history;
use App\Http\Controllers\basicVision;
use App\Http\Controllers\BangabandhuController;
use App\Http\Controllers\SendEmailController;
use App\Http\Controllers\GoldenJubileeController;
use App\Http\Controllers\FormControllerController;
use App\Http\Controllers\FormviewController;
use App\Http\Controllers\StudentController;
use App\Http\Controllers\StudentMastersController;
use App\Http\Controllers\ExamCommitteesController;
use App\Http\Controllers\ExamNameController;
use App\Http\Controllers\ExamDutyRoasterController;
use App\Http\Controllers\StudenClassController;
use App\Http\Controllers\CourseNameController;
use App\Http\Controllers\StudentResultController;
use App\Http\Controllers\EmployeeController;
use App\Http\Controllers\BusScheduleController;
use App\Http\Controllers\BusTerminalController;
use App\Http\Controllers\JournalController;
use App\Http\Controllers\ClassScheduleController;
use App\Http\Controllers\InternalMailController;
use App\Http\Controllers\OnlinePortalController;
use App\Http\Controllers\VideoClipController;
use App\Http\Controllers\FacultyController;
use App\Http\Controllers\SubofsubmenuController;
use App\Http\Controllers\AcademicController;
use App\Http\Controllers\HonorariumDistributeController;
use App\Http\Controllers\ExamAttendenceController;
use App\Http\Controllers\PhotoGalleryController;
use App\Http\Controllers\DepartmentNoticeController;
use App\Http\Controllers\BuldingNameController;
use App\Http\Controllers\RoomNoController;
use App\Http\Controllers\ExamsetupController;
use App\Http\Controllers\ExamSeatcardController;
use App\Http\Controllers\GlanceSeatPlanController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\SeatPlanController;
use App\Http\Controllers\CocurricularteacherController;
use App\Http\Controllers\DepartmentResultController;
use App\Http\Controllers\DepartmentParticularResultController;
use App\Http\Controllers\ExamRoutineController;
use App\Http\Controllers\RoutineTimeController;
use App\Http\Controllers\DRAnalysisController;
use App\Http\Controllers\ImportExportController;
use App\Http\Controllers\DrExamSeatplanController;
use App\Http\Controllers\SeatAllotmentController;
use App\Http\Controllers\HostelNoticeBoardController;
use App\Http\Controllers\HostelIdCardController;
use App\Http\Controllers\CocurricularNoticeController;
use App\Http\Controllers\CoCurricularManageController;
use App\Http\Controllers\ComplainCornarController;
use App\Http\Controllers\StudentSessionManageController;
use App\Http\Controllers\StudentPromotionController;
use App\Http\Controllers\StudentResultFirstYearController;
use App\Http\Controllers\StudentResultSecondYearController;
use App\Http\Controllers\StudentResultThirdYearController;
use App\Http\Controllers\StudentResultFourthYearController;
use App\Http\Controllers\StudentConsolidatedResultFinalYearController;
use App\Http\Controllers\ApalinksController;
use App\Http\Controllers\ApaNocController;
use App\Http\Controllers\NislinksController;
use App\Http\Controllers\NisNoticeViewController;
use App\Http\Controllers\InnovativelinksController;
use App\Http\Controllers\InnovativeNoticeViewController;
use App\Http\Controllers\ElearninglinksController;
use App\Http\Controllers\ElearningNoticeViewController;
use App\Http\Controllers\JournalOfSaadatController;
use App\Http\Controllers\JournalOfMagaginController;
use App\Http\Controllers\OtherPublicationController;
use App\Http\Controllers\DeptBgImageController;
use App\Http\Controllers\StudentMeritListFirstYearController;
use App\Http\Controllers\StudentMeritListSecondYearController;
use App\Http\Controllers\StudentMeritListThirdYearController;
use App\Http\Controllers\StudentMeritListFourthYearController;
use App\Http\Controllers\StudentInCourseFirstYearController;
use App\Http\Controllers\StudentInCourseSecondYearController;
use App\Http\Controllers\StudentInCourseThirdYearController;
use App\Http\Controllers\StudentInCourseFourthYearController;
use App\Http\Controllers\StudentInCourseController;
use App\Http\Controllers\HostelBuldingNameController;
use App\Http\Controllers\HostelFloorController;
use App\Http\Controllers\HostelRoomController;
use App\Http\Controllers\HostelSeatViewListController;
use App\Http\Controllers\HostelStudentController;
use App\Http\Controllers\HostelGeneralInfoController;
use App\Http\Controllers\HostelApplicationController;
use App\Http\Controllers\HostelHeadContactController;
use App\Http\Controllers\HostelGalleryController;
use App\Http\Controllers\NoReturnBookController;
use App\Http\Controllers\LibraryNoticeController;
use App\Http\Controllers\LibraryGalleryController;
use App\Http\Controllers\StudentHonoursSecoundYearController;
use App\Http\Controllers\StudentHonoursThirdYearController;
use App\Http\Controllers\StudentHonoursFourthYearController;
use App\Http\Controllers\StudentPreliminaryToMastersController;
use App\Http\Controllers\StudentMastersFinalController;
use App\Http\Controllers\StudentResultPreliminaryToMastersController;
use App\Http\Controllers\StudentResultMastersFinalController;
use App\Http\Controllers\StudentMeritListMastersFinalController;
use App\Http\Controllers\StudentMeritListPreliminaryToMastersController;
use App\Http\Controllers\StudentHonoursFirstYearEditableController;
use App\Http\Controllers\DegreeClassController;
use App\Http\Controllers\DegreeCourseController;
use App\Http\Controllers\DegreeFirstYearStudentController;
use App\Http\Controllers\DegreeSecoundYearStudentController;
use App\Http\Controllers\DegreeThirdYearStudentController;
use App\Http\Controllers\DegreeFourthYearStudentController;
use App\Http\Controllers\DegreeResultFirstYearStudentController;
use App\Http\Controllers\DegreeResultSecoundYearStudentController;
use App\Http\Controllers\DegreeResultThirdYearStudentController;
use App\Http\Controllers\DegreeResultFourthYearStudentController;
use App\Http\Controllers\DegreeConsolidatedResultFinalYearController;
use App\Http\Controllers\DegreeMeritListController;
use App\Http\Controllers\StudentInCoursePreliminaryController;
use App\Http\Controllers\StudentInCourseMastersFinalController;
use App\Http\Controllers\DegreeInCourseMarksFirstYearController;
use App\Http\Controllers\DegreeInCourseMarksSecoundYearController;
use App\Http\Controllers\DegreeInCourseMarksThirdYearController;
use App\Http\Controllers\DegreeInCourseMarksFourthYearController;
use App\Http\Controllers\StudentPrliminaryEditableController;
use App\Http\Controllers\DegreeBackgroundImageController;
use App\Http\Controllers\DegreeHistroyController;
use App\Http\Controllers\DegreeMissionVissionController;
use App\Http\Controllers\DegreeOfHeadController;
use App\Http\Controllers\DegreeTeacherController;
use App\Http\Controllers\DegreeStaffController;
use App\Http\Controllers\DegreePhotoGalleryController;
use App\Http\Controllers\DegreePhotoNoticeController;
use App\Http\Controllers\DegreeClassScheduleController;
use App\Http\Controllers\DegreeSyllabusController;
use App\Http\Controllers\DegreeFirstYearEditabelController;
use App\Http\Controllers\DegreeResultController;
use App\Http\Controllers\SeminarLibraryCardController;
use App\Http\Controllers\SeminarBookStockController;
use App\Http\Controllers\SeminarBookIssueController;
use App\Http\Controllers\SeminarBookRefundController;
use App\Http\Controllers\SeminarBookNoReturnController;
use App\Http\Controllers\SeminarNoticeController;
use App\Http\Controllers\SeminarGalleryController;
use App\Http\Controllers\SeminarPersonnelController;
use App\Http\Controllers\SeminarCardInstructionController;
use App\Http\Controllers\ExamMasterDutyRosterController;
use App\Http\Controllers\ExamMasterDutyRosterEditableController;
use App\Http\Controllers\ExamRoomwiseMasterDutyController;
use App\Http\Controllers\ExamRoomwiseEditableController;
use App\Http\Controllers\ExamDrRoutineController;
use App\Http\Controllers\ExamDrGlanceSeatListController;
use App\Http\Controllers\StudentReceipNoteController;
use App\Http\Controllers\HostelIdCardNoteController;
use App\Http\Controllers\LibraryLogoController;
use App\Http\Controllers\HostelLogoSignController;
use App\Http\Controllers\DegreeLogoSignController;
use App\Http\Controllers\DegreeStudentIdCardNoteController;
use App\Http\Controllers\SeminarLogoSignController;
use App\Http\Controllers\DepartmentStudentNoteController;
use App\Http\Controllers\DepartmentLogoSignController;
use App\Http\Controllers\DegreeTeacherHonourBoardController;
use App\Http\Controllers\DegreeInternalMailController;
use App\Http\Controllers\HonoursStudentPromoteController;
use App\Http\Controllers\DegreeStudentPromoteController;
use App\Http\Controllers\DepartmentSettingController;
use App\Http\Controllers\CourseFeeController;
use App\Http\Controllers\RegularFeeController;
use App\Http\Controllers\ConditionalPromotedFeeController;
use App\Http\Controllers\ImprovementFeeController;
use App\Http\Controllers\IrregularFormFillUpFeeController;
use App\Http\Controllers\IrregularNonFormFillUpFeeController;
use App\Http\Controllers\FailStudentFeeController;
use App\Http\Controllers\DegreeCourseFeeController;
use App\Http\Controllers\DegreeRegularFeeController;
use App\Http\Controllers\DegreeIrregularFeeController;
use App\Http\Controllers\DegreeIrregularNonFormFillupController;
use App\Http\Controllers\DegreeImprovementController;
use App\Http\Controllers\DegreeConditionalPromotedController;
use App\Http\Controllers\DegreeFailCoursFeeController;

Route::view('/welcome', 'welcome');
 
Route::get('/', [HomeController::class, 'index'])->name('index');
Route::post('/department-loginaction', [DepartmentmanageController::class, 'loginaction']);
Route::get('/department_dashboard', [DepartmentmanageController::class, 'departmentDashboard']);
Route::get('menu/{id1}/{id2}', [NavbarController::class , 'menu']);
Route::get('/syllabus', [HomeController::class , 'syllabus']);
Route::get('/academy/{id}', [HomeController::class , 'academy']);
Route::get('/principalview', [HomeController::class , 'principalview']);
Route::get('/principaldetails/{id}', [HomeController::class , 'principaldetails']);
Route::get('/viceprincipalview', [HomeController::class , 'viceprincipalview']);
Route::get('/viceprincipaldetails/{id}', [HomeController::class , 'viceprincipaldview']);
Route::get('/academincouncilview', [HomeController::class , 'academincouncilview']);
Route::get('/academic_calender', [HomeController::class , 'academic_calender']);
Route::get('/allacademic/{id}/{type}', [NavbarController::class , 'academics']);
Route::get('location', [NavbarController::class, 'location']);
Route::post('/complain_massage', [NavbarController::class,'complainMassage'])->name('complainMassage');
Route::get('departmentdetails/{id}', [NavbarController::class ,'arts']);
Route::get('/t_council', [HomeController::class , 't_council']);
Route::get('/t_councilhbview', [HomeController::class , 't_councilhbview']);
Route::get('/teacherview', [HomeController::class , 't_view']);
Route::get('/staffview', [HomeController::class , 'staffview']);
Route::get('/principal-honour-board', [HomeController::class ,'principalHonourBoard']);
Route::get('/viceprincipal-honour-board', [HomeController::class ,'vicePrincipalHonourBoard']);
Route::get('/noticeboardview', [HomeController::class ,'noticeboardview']);
Route::get('nocview', [HomeController::class ,'nocview']);
Route::get('/officeorderview', [HomeController::class ,'officeorderview']);
Route::get('/personnel', [HomeController::class ,'libraryview']);
Route::get('sportteacherview', [NavbarController::class ,'sportteacherview']);
Route::get('sportchampionview', [NavbarController::class ,'sportchampionview']);
Route::get('sportnoticeview', [NavbarController::class ,'sportnoticeview']);
Route::get('hostel_notice', [NavbarController::class ,'hostelnotice']);
Route::get('library_notices', [NavbarController::class ,'Librarynotice']);
Route::get('rules_regulation', [NavbarController::class ,'rulesRegulation']);
Route::get('general_information', [NavbarController::class ,'generalInformation']);
Route::get('hostel_application', [NavbarController::class ,'hostelApplication']);
Route::get('hostel_head_contact', [NavbarController::class ,'hostelHeadContact']);
Route::get('hostel_gallary', [NavbarController::class ,'hostelGallary']);
Route::get('library_gallary', [NavbarController::class ,'LibraryGallary']);
Route::get('arts/{id}', [NavbarController::class ,'arts']);
Route::get('goldenJubilee/{id}', [NavbarController::class ,'goldenJubilee']);
Route::get('bongobondhu/{id}', [NavbarController::class ,'bongobondhu']);
Route::get('newsview/{id}', [NavbarController::class ,'newsview']);
Route::get('eventview/{id}', [NavbarController::class ,'eventview']);
Route::get('froms', [NavbarController::class ,'froms']);
Route::get('apa-noc-view', [NavbarController::class ,'apanocview']);
Route::get('busschedule', [NavbarController::class ,'busschedule']);
Route::get('fromsview/{id}', [NavbarController::class ,'fromsview']);
Route::get('apa-notices-view', [NavbarController::class ,'apaNoticeView']);
Route::get('nis-notices-view', [NavbarController::class ,'nisNoticeView']);
Route::get('innovative-notices-view', [NavbarController::class ,'innovativeNoticeView']);
Route::get('elearning-notices-view', [NavbarController::class ,'elearningNoticeView']);
Route::get('class_schedules/{id}', [NavbarController::class ,'class_schedules']);
Route::get('Principal_Office/annual_committee', [NavbarController::class ,'annual_committee']);
Route::get('journals-of-saadat-college', [NavbarController::class ,'journals']);
Route::get('college-magazines', [NavbarController::class ,'collegeMagazines']);
Route::get('other-publications', [NavbarController::class ,'otherPublications']);
Route::get('send-email', [SendEmailController::class, 'index']);
Route::get('librainansearch', [NavbarController::class, 'Librainansearch']);
Route::get('librarybookstock', [NavbarController::class, 'Librarybookstock']);
Route::get('bookstocks', [HomeController::class ,'bookstockview']);
Route::get('department_notice/{id}', [NavbarController::class ,'department_notice']);

Route::get('/department-login', [DepartmentmanageController::class, 'index']);
Route::get('history', [NavbarController::class, 'aboutus']);
Route::get('vision', [NavbarController::class, 'vision']);
Route::get('contactus', [NavbarController::class, 'contactus']);
Route::get('admission', [NavbarController::class, 'admission']);
Route::get('admission-registration', [NavbarController::class, 'admissionRegistration']);
Route::post('admission', [NavbarController::class, 'admissionStore']);
Route::get('admission_departinfo/{id}/{depart_id}', [NavbarController::class,'admissionDepartInfo']);
Route::post('form-fillUp-fee', [NavbarController::class, 'admissionLogin']);
Route::post('form-fillUp-fee-store', [NavbarController::class, 'formFillUpFeeStore']);
Route::get('regi_typeInfo/{typevalue}/{departId}/{classId}', [NavbarController::class, 'admissionType']);
Route::get('admission_departInfo/{depart_id}', [NavbarController::class,'admissionDepartClassInfo']);
Route::get('admission_classInfo/{id}/{depart_id}', [NavbarController::class,'admissionSessionInfo']);
Route::get('co_curricular/{slug}', [NavbarController::class, 'cocurricularManage']);
Route::get('principalsearch/{id}', [NavbarController::class, 'principalsearch']);
Route::get('sportteacherview', [NavbarController::class ,'sportteacherview']);
Route::get('sportchampionview', [NavbarController::class ,'sportchampionview']);
Route::get('studentsearch/{id}', [NavbarController::class ,'studentsearch']);
Route::get('studentsearch', [NavbarController::class ,'studentSearch']);

Route::get('result', [NavbarController::class ,'resultlogin']);
Route::post('studentresult', [NavbarController::class ,'studentresult']);


 Route::middleware('department')->group(function () {
        Route::get('/department-dashboard', [DepartmentmanageController::class, 'dashboard']);
        Route::get('/department-history', [DepartmentmanageController::class, 'depart_history']);
        Route::get('/department-vision', [DepartmentmanageController::class, 'depart_vision']);
        Route::resource('mission-vision', basicVision::class);
        Route::resource('department_history', college_history::class);
        Route::resource('department_image', DeptBgImageController::class);
        Route::resource('department_setting', DepartmentSettingController::class);
 
        Route::get('department-historyedit/{id}', [DepartmentmanageController::class, 'depart_historyedit']);
        Route::post('/historyeditaction', [DepartmentmanageController::class, 'historyeditaction']);
        Route::get('department-visionedit/{id}', [DepartmentmanageController::class, 'depart_visionedit']);
        Route::post('/visioneditaction', [DepartmentmanageController::class, 'visioneditaction']);
        Route::resource('headofdepartment', HeadofdepartmentController::class);
        Route::resource('department-teacher', TeacherController::class);
        Route::get('/teacher-honour-board', [TeacherController::class, 'teacherHonourBoard'])->name('teacher-honour-board');
        Route::resource('id-card-instruction', DepartmentStudentNoteController::class);
        Route::resource('id-card-logosign', DepartmentLogoSignController::class);
        Route::resource('honours-first-year-students', StudentController::class);
        Route::post('honours_secound_student_promote', [HonoursStudentPromoteController::class, 'HonoursSecondYearStudentPromote']);
        Route::post('honours_third_student_promote', [HonoursStudentPromoteController::class, 'HonoursThirdYearStudentPromote']);
        Route::post('honours_fourth_student_promote', [HonoursStudentPromoteController::class, 'HonoursFourthYearStudentPromote']);

        Route::post('honours_first_year_idcard', [StudentController::class,'HonoursFirstYearIDCard']);
        Route::get('student_idcard/{id}', [StudentController::class, 'StudentCardDetails'])->name('student_idcard');
        Route::get('honors_firstyear_studycertificate/{id}', [StudentController::class, 'honorsFirstYearStudyCertificate']);
        Route::get('student_firstyear_editable/{session}', [StudentHonoursFirstYearEditableController::class, 'EditData'])
        ->name('student_firstyear_editable');
        Route::post('tabledit/action', [StudentHonoursFirstYearEditableController::class, 'EditDataAction'])
        ->name('tabledit.action');
        Route::get('student_preliminary_editable/{session}', [StudentPrliminaryEditableController::class, 'PreliminaryEditData'])
        ->name('student_preliminary_editable');
        Route::post('preliminarytabledit/action', [StudentPrliminaryEditableController::class, 'PreliminaryEditDataAction'])
        ->name('preliminarytabledit.action');
        Route::get('student_masters_editable/{session}', [StudentPrliminaryEditableController::class, 'MastersEditData'])
        ->name('student_masters_editable');
        Route::post('masterstabledit/action', [StudentPrliminaryEditableController::class, 'MastersEditDataAction'])
        ->name('masterstabledit.action');
        Route::resource('honours-secound-year-students', StudentHonoursSecoundYearController::class);
        Route::resource('honours-third-year-students', StudentHonoursThirdYearController::class);
        Route::resource('honours-fourth-year-students', StudentHonoursFourthYearController::class);
        Route::resource('preliminary-masters-students', StudentPreliminaryToMastersController::class);
        Route::resource('masters-Final-students', StudentMastersFinalController::class);
        Route::get('studentSessionData/{session}', [StudentController::class, 'studentSessionData']);
        Route::get('updateStudentData', [StudentController::class, 'updateStudentData']);
        Route::resource('masters-students', StudentMastersController::class);

        Route::post('honours_second_year_idcard', [StudentHonoursSecoundYearController::class,'HonoursSecondYearIDCard']);
        Route::get('second_year_student_idcard/{id}', [StudentHonoursSecoundYearController::class, 'SecondStudentCardDetails'])->name('second_year_student_idcard');
        Route::get('honors_secondyear_studycertificate/{id}', [StudentHonoursSecoundYearController::class, 'honorsSecondYearStudyCertificate']);
        Route::post('honours_third_year_idcard', [StudentHonoursThirdYearController::class,'HonoursThirdYearIDCard']);
        Route::get('third_year_student_idcard/{id}', [StudentHonoursThirdYearController::class, 'ThirdStudentCardDetails'])->name('third_year_student_idcard');
        Route::get('honors_thirdyear_studycertificate/{id}', [StudentHonoursThirdYearController::class, 'honorsThirdYearStudyCertificate']);
        Route::post('honours_four_year_idcard', [StudentHonoursFourthYearController::class,'HonoursFourYearIDCard']);
        Route::get('four_year_student_idcard/{id}', [StudentHonoursFourthYearController::class, 'FourStudentCardDetails'])->name('four_year_student_idcard');
        Route::get('honors_fourthyear_studycertificate/{id}', [StudentHonoursFourthYearController::class, 'honorsFourthYearStudyCertificate']);
        Route::get('honors_testimonial/{id}', [StudentHonoursFourthYearController::class, 'honorsTestimonial']);

        Route::post('student_preliminary_idcard', [StudentPreliminaryToMastersController::class,'StudentPreliminaryIDCard']);
        Route::get('preliminary_student_idcard/{id}', [StudentPreliminaryToMastersController::class, 'PreliminaryStudentCardDetails'])->name('preliminary_student_idcard');
        Route::get('preliminary_studycertificate/{id}', [StudentPreliminaryToMastersController::class, 'PreliminaryStudyCertificate']);
        Route::post('student_masterfinal_idcard', [StudentMastersFinalController::class,'StudentMasterfinalIDCard']);
        Route::get('masterfinal_student_idcard/{id}', [StudentMastersFinalController::class, 'MasterfinalStudentCardDetails'])->name('masterfinal_student_idcard');
        Route::get('masterfinal_studycertificate/{id}', [StudentMastersFinalController::class, 'MasterfinalStudyCertificate']);
        Route::get('masters_testimonial/{id}', [StudentMastersFinalController::class, 'mastersTestimonial']);

        Route::post('student_import', [StudentController::class,'StudentImport']);
        Route::post('scound_student_import', [StudentHonoursSecoundYearController::class,'secoundYearStudentImport']);
        Route::post('third_student_import', [StudentHonoursThirdYearController::class,'thirdYearStudentImport']);
        Route::post('fourth_student_import', [StudentHonoursFourthYearController::class,'fourthYearStudentImport']);
        Route::post('preliminary_student_import', [StudentPreliminaryToMastersController::class,'preliminaryStudentImport']);
        Route::post('masters_final_student_import', [StudentMastersFinalController::class,'mastersFinalStudentImport']);
        Route::resource('department-class', StudenClassController::class);
        Route::resource('studentsessionmanage', StudentSessionManageController::class);
        Route::get('student-promote', [StudentPromotionController::class, 'studentPromote']);
        Route::resource('department-course', CourseNameController::class);
        Route::resource('department-course-fee', CourseFeeController::class);
        Route::get('coursefee_session/{id}',[CourseFeeController::class, 'StudentFeeSession'] );
        Route::get('getcoursefeesession', [CourseFeeController::class, 'getCourseFeeSession'])->name('getcoursefeesession');
        Route::resource('regular-fee', RegularFeeController::class);
        Route::resource('irregular-form-fillup-fee', IrregularFormFillUpFeeController::class);
        Route::get('class_session/{id}',[IrregularFormFillUpFeeController::class, 'StudentClassSession'] );
        Route::get('getsession', [IrregularFormFillUpFeeController::class, 'getSession'])->name('conditional-promoted-fee.getsession');
        Route::resource('irregular-nonform-fillup-fee', IrregularNonFormFillUpFeeController::class);
        Route::resource('improvement-fee', ImprovementFeeController::class);
        Route::resource('conditional-promoted-fee', ConditionalPromotedFeeController::class);
        Route::resource('fail-course-fee', FailStudentFeeController::class);
        Route::resource('department_staff', StaffController::class);
        Route::resource('students-result', StudentResultController::class);
        //Honourse 1st year
        Route::resource('students-result-first-year', StudentResultFirstYearController::class);
        Route::get('student_year_session/{id}',[StudentResultFirstYearController::class, 'StudentYearSession'] );
        Route::post('getUserbyid',[StudentResultFirstYearController::class, 'getUserbyid'] );
        Route::get('mark-sheet-download/{student_id}',[StudentResultFirstYearController::class, 'mark_sheet_download'] );

        //Honourse 2nd year
        Route::resource('students-result-second-year', StudentResultSecondYearController::class);
        Route::get('student_secoundyear_session/{id}',[StudentResultSecondYearController::class, 'StudentSecoundYearSession'] );
        Route::post('getUserbyidSecound',[StudentResultSecondYearController::class, 'getUserbyidSecound'] );
        Route::get('secound-year-marksheet/{registration_no}',[StudentResultSecondYearController::class, 'secoundYearMarksheet'] );
        //Honourse 3rd year
        Route::resource('students-result-third-year', StudentResultThirdYearController::class);
        Route::get('student_third_year_session/{id}', [StudentResultThirdYearController::class, 'StudentThirdYear']);
        Route::post('getUserbyidthird', [StudentResultThirdYearController::class, 'getUserbyidthird']);
        Route::get('third-year-marksheet/{registration_no}',[StudentResultThirdYearController::class, 'thirdYearMarksheet'] );
        //Honourse 4th year
        Route::resource('students-result-fourth-year', StudentResultFourthYearController::class);
        Route::get('student_fourth_year_session/{id}', [StudentResultFourthYearController::class, 'StudentFourthYear']);
        Route::post('getUserbyidFourth', [StudentResultFourthYearController::class, 'getUserbyidFourth']);
        Route::get('fourth-year-marksheet/{registration_no}',[StudentResultFourthYearController::class, 'fourthYearMarksheet'] );
        Route::get('consolidated-result/{registration_no}',[StudentConsolidatedResultFinalYearController::class, 'consolidated_result'] );
        
        Route::resource('preliminary-masters-result', StudentResultPreliminaryToMastersController::class);
        Route::get('student_preliminary/{id}', [StudentResultPreliminaryToMastersController::class, 'studentPreliminary']);
        Route::post('getUserbyidPreliminary', [StudentResultPreliminaryToMastersController::class, 'getUserbyidPreliminary']);
        Route::get('preliminary-masters-marksheet/{registration_no}',[StudentResultPreliminaryToMastersController::class, 'preliminaryMarksheet'] );
        
        Route::resource('masters-final-result', StudentResultMastersFinalController::class);
        Route::get('student_mastersfinal/{id}', [StudentResultMastersFinalController::class, 'studentMastersFinal']);
        Route::post('getUserbyidMastersFinal', [StudentResultMastersFinalController::class, 'getUserbyidMastersFinal']);
        Route::get('masters-final-marksheet/{registration_no}',[StudentResultMastersFinalController::class, 'masterFinalMarksheet'] );
        //Honourse Merit list
        Route::resource('first-year-merit-list', StudentMeritListFirstYearController::class);
        Route::post('studentfirstmerit_Userbyid',[StudentMeritListFirstYearController::class, 'Studentmerit_UserId'] );
        Route::post('first-year-merit-list/export-pdf',[StudentMeritListFirstYearController::class, 'MeritexportToPDF'] );
        Route::resource('second-year-merit-list', StudentMeritListSecondYearController::class);
        Route::post('studentsecondmerit',[StudentMeritListSecondYearController::class, 'StudentSecondmerit'] );
        Route::post('second-year-merit-list/export-pdf',[StudentMeritListSecondYearController::class, 'SecondMeritexportToPDF'] );
        Route::resource('third-year-merit-list', StudentMeritListThirdYearController::class);
        Route::post('studentthirdmerit',[StudentMeritListThirdYearController::class, 'StudentThirdmerit'] );
        Route::post('third-year-merit-list/export-pdf',[StudentMeritListThirdYearController::class, 'ThirdMeritexportToPDF'] );
        Route::resource('fourth-year-merit-list', StudentMeritListFourthYearController::class);
        Route::post('studentfourthmerit',[StudentMeritListFourthYearController::class, 'StudentFourthmerit'] );
        Route::post('fourth-year-merit-list/export-pdf',[StudentMeritListFourthYearController::class, 'FourthMeritexportToPDF'] );
        Route::resource('preliminary-merit-list', StudentMeritListPreliminaryToMastersController::class);
        Route::post('studentpreliminarymerit',[StudentMeritListPreliminaryToMastersController::class, 'StudentPreliminarymerit'] );
        Route::post('preliminary-merit-list/export-pdf',[StudentMeritListPreliminaryToMastersController::class, 'PreliminaryMeritexportToPDF'] );
        Route::resource('masters-final-merit-list', StudentMeritListMastersFinalController::class);
        Route::post('studentmastersfinalmerit',[StudentMeritListMastersFinalController::class, 'StudentMasterfinalmerit'] );
        Route::post('mastersfinal-merit-list/export-pdf',[StudentMeritListMastersFinalController::class, 'MasterfinalMeritexportToPDF'] );
        
        Route::post('getUserId',[StudentInCourseController::class, 'getUserId'] );
        Route::post('incourse-result/export-pdf',[StudentInCourseController::class, 'exportToPDF'] );
        //Honours First Year Incours
        Route::resource('first-year-incourse-mark', StudentInCourseFirstYearController::class);
        Route::post('getIncourseFirst',[StudentInCourseFirstYearController::class, 'getIncourseFirst'] );
        Route::post('incourse-first-year-result/export-pdf',[StudentInCourseFirstYearController::class, 'FirstYearExportToPDF'] );
        
        Route::resource('second-year-incourse-mark', StudentInCourseSecondYearController::class);
        Route::post('getIncourseSecound',[StudentInCourseSecondYearController::class, 'getIncourseSecound'] );
        Route::post('incourse-second-year-result/export-pdf',[StudentInCourseSecondYearController::class, 'SecondYearExportToPDF'] );
        
        Route::resource('third-year-incourse-mark', StudentInCourseThirdYearController::class);
        Route::post('getIncourseThird',[StudentInCourseThirdYearController::class, 'getIncourseThird'] );
        Route::post('incourse-third-year-result/export-pdf',[StudentInCourseThirdYearController::class, 'ThirdYearExportToPDF'] );
        
        Route::resource('fourth-year-incourse-mark', StudentInCourseFourthYearController::class);
        Route::post('getIncourseFourth',[StudentInCourseFourthYearController::class, 'getIncourseFourth'] );
        Route::post('incourse-fourth-year-result/export-pdf',[StudentInCourseFourthYearController::class, 'FourthYearExportToPDF'] );
        
        Route::resource('preliminary-incourse-mark', StudentInCoursePreliminaryController::class);
        Route::post('getIncoursePreliminary',[StudentInCoursePreliminaryController::class, 'getIncoursePreliminary'] );
        Route::post('incourse-preliminary-year-result/export-pdf',[StudentInCoursePreliminaryController::class, 'PreliminaryYearExportToPDF'] );
        
        Route::resource('masters-final-incourse-mark', StudentInCourseMastersFinalController::class);
        Route::post('getIncourseMaster',[StudentInCourseMastersFinalController::class, 'getIncourseMaster'] );
        Route::post('incourse-masterfinal-year-result/export-pdf',[StudentInCourseMastersFinalController::class, 'MasterFinalYearExportToPDF'] );
        
        Route::get('searchstudent',[StudentResultController::class, 'searchstudent'] );
        Route::post('searchyear',[StudentResultController::class, 'searchyear'] );
        Route::get('department-syllabus',[AcademicController::class, 'syllabusmanage'] );
        Route::get('syllabusedit/{id}',[AcademicController::class, 'edit'] );
        Route::post('department-syllabusereate', [AcademicController::class, 'syllabusereate']);
       Route::post('searchsubjet/{id}',[StudentResultController::class, 'searchsubjet'] );
       Route::resource('department-class_schedules', ClassScheduleController::class);
        Route::get('departmentsentinternal_mails', [InternalMailController::class, 'department_sentinternal']);
        Route::get('sentmail-delete/{id}', [InternalMailController::class, 'distroy']);
      Route::get('inboxmail-delete/{id}', [InternalMailController::class, 'inboxdistroy']);
      Route::get('department_sentmaildetails/{id}', [InternalMailController::class, 'department_sentmaildetails']);
      Route::post('departmentstore', [InternalMailController::class, 'departmentstore']);
      Route::get('dchange_status/{id}', [InternalMailController::class, 'status']);
      Route::get('dchange_status/{id}', [InternalMailController::class, 'status']);
      Route::post('postvalue', [StudentResultController::class, 'postvalue']);
      Route::get('department-inboxinternal_mails', [InternalMailController::class, 'department_inboxinternal']);
         Route::resource('photo_galleries', PhotoGalleryController::class);
         Route::resource('department-notice', DepartmentNoticeController::class);
        Route::post('/department-out', [DepartmentmanageController::class, 'department_out']);
        Route::resource('departmentresult',DepartmentResultController::class);
        //Seminar Manage
        Route::resource('seminar-id-card',SeminarLibraryCardController::class);
        Route::post('seminar_card_export',[SeminarLibraryCardController::class, 'SeminarCardExportToPDF'] );
        Route::get('seminar_carddetails/{id}', [SeminarLibraryCardController::class, 'seminarCardDetails'])->name('seminar_carddetails');
        // Route::get('scarddetails/{id}', [LibraryCardController::class, 'scarddetails'])->name('scarddetails');
        Route::get('seminar_classInfo/{id}', [SeminarLibraryCardController::class,'seminarClassInfo']);
        Route::post('seminarstudentInfo',[SeminarLibraryCardController::class, 'seminarStudentInfo'] );
        Route::post('seminarstuallInfo',[SeminarLibraryCardController::class, 'seminarstuallInfo'] );
        Route::resource('seminar-book-stock',SeminarBookStockController::class);
        Route::resource('seminar-book-issue',SeminarBookIssueController::class);
        Route::get('seminarbookID/{id}', [SeminarBookIssueController::class,'seminarbookName']);
        Route::resource('seminar-book-refund',SeminarBookRefundController::class);
        Route::get('seminarbookName/{id}', [SeminarBookRefundController::class,'seminarBookDetails']);
        Route::resource('seminar-book-no-return',SeminarBookNoReturnController::class);
        Route::resource('seminar_notice',SeminarNoticeController::class);
        Route::resource('seminar_gallery',SeminarGalleryController::class);
        Route::resource('seminar-personnel',SeminarPersonnelController::class);
        Route::resource('seminar-card-instruction',SeminarCardInstructionController::class);
        Route::resource('seminar-logo-sign',SeminarLogoSignController::class);
        Route::get('/seminar_book_stock_pdf', [SeminarBookStockController::class,'seminarBookStockPdf']);
        Route::get('/seminar_book_issue_pdf', [SeminarBookIssueController::class,'seminarBookIssuePdf']);
        Route::get('/seminar_book_refund_pdf', [SeminarBookRefundController::class,'seminarBookRefundPdf']);
        Route::get('/seminar_book_no_return_pdf', [SeminarBookNoReturnController::class,'seminarBookNoReturnPdf']);
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

      Route::middleware('auth')->group(function () {
      Route::get('/superadmin', [SuperAdminController::class, 'index'])->name('superadmin');
      Route::resource('usermanage', UserManageController::class);
      // Route::post('/login_user',[UserManageController::class,'loginValidation']);
      Route::resource('faculty', FacultyController::class);
      Route::resource('department-entry', DepartmentController::class);
      Route::resource('exviceprincipal', ExViceprincipalController::class);
      Route::resource('administration', AdministrationController::class);
      Route::resource('basicinfo', BasicController::class);
      Route::resource('basichistory', BasicController::class);
      Route::resource('menumanage', MenuController::class);
      Route::resource('submenumanage', SubmenuController::class);
      Route::resource('events', EventController::class);
      Route::resource('department', DepartmentController::class);
      Route::resource('slideshow', SlideController::class);
      Route::resource('massageshow', MessageController::class);
      Route::resource('principaleinfo', PrincipalController::class);
      Route::get('principalsentinternal_mails', [PrincipalController::class,'sent']);
      Route::get('principal-sent-mail-delete/{id}', [PrincipalController::class,'distroy']);
      Route::get('principal_inboxinternal_mails', [PrincipalController::class,'inbox']);
      Route::get('principal-inbox-mail-delete/{id}', [PrincipalController::class,'inboxdistroy']);
      Route::post('email_store', [PrincipalController::class, 'emailStore']);
      Route::get('principalemaildetails/{id}', [PrincipalController::class, 'details']);
      Route::resource('principaledetails', PrincipaldetailsController::class);
      Route::resource('viceprincipalinfo', ViceprincipalController::class);
      Route::resource('viceprincipaledetails', VicepdetailsController::class);
      Route::resource('academiccouncils', AcademinCouncilController::class);
      Route::resource('teachercouncil', TeacherCouncilController::class);
      Route::resource('teachercouncilhb', TeacherCouncilHBController::class);
      Route::resource('teacher', TeacherContclass_sessionroller::class);
      Route::resource('staff', StaffController::class);
      Route::resource('exprincipaleinfo', ExprincipalController::class);
      Route::resource('video_clips', VideoClipController::class);
      Route::resource('online_portals', OnlinePortalController::class);
      Route::resource('qucklinks', QucklinksController::class);
      Route::resource('apalinks', ApalinksController::class);
      Route::resource('apa-notice', ApaNocController::class);
      Route::resource('nislinks', NislinksController::class);
      Route::resource('nis-notice', NisNoticeViewController::class);
      Route::resource('innovative-links', InnovativelinksController::class);
      Route::resource('innovative-notice', InnovativeNoticeViewController::class);
      Route::resource('elearning-links', ElearninglinksController::class);
      Route::resource('elearning-notice', ElearningNoticeViewController::class);
      Route::resource('news', BreakingNewsController::class);
      Route::resource('notice_board', NoticeBoardController::class);
      Route::resource('noc', NOCController::class);
      Route::resource('office_order', OfficeOrderController::class);
      Route::resource('annual', AnnualCommitteesController::class);
      Route::resource('bangabandhumanage', BangabandhuController::class);
      Route::resource('goldenJubileemanage', GoldenJubileeController::class);    
      Route::resource('formsmanage', FormControllerController::class);
      Route::resource('complaincornar', ComplainCornarController::class);
      Route::get('froms/{id}', [FormviewController::class ,'fromsview']);
      Route::resource('academicmanage', AcademicController::class);
      //Route::get('/principal', [AdministrationController::class, 'principal'])->name('principal');
      Route::get('/viceprincipal', [AdministrationController::class, 'viceprincipal'])->name('viceprincipal');
      Route::resource('cinstruction', InstrucionController::class);
      Route::resource('examname', ExamNameController::class); 
      Route::resource('examcommittee', ExamCommitteesController::class);
      Route::resource('honorarium_distributes', HonorariumDistributeController::class);
      Route::get('/prnpriview','InstrucionController@prnpriview');
      Route::resource('library_personnel', LibrarianController::class);
      Route::resource('library_notice', LibraryNoticeController::class);
      Route::resource('library_gallery', LibraryGalleryController::class);
      Route::resource('slibrary_card', LibraryCardController::class);
      Route::resource('library_signature', LibraryLogoController::class);
      Route::post('library_card_export',[LibraryCardController::class, 'LibraryCardExportToPDF'] );
      Route::resource('bookissue', BookIssueController::class);
      Route::get('bookID/{id}', [BookIssueController::class,'bookName']);
      Route::resource('bookstock', BookstockController::class);
      Route::resource('refund', BookRefundController::class);
      Route::resource('book_no_retrn', NoReturnBookController::class);
      Route::get('bookName/{id}', [BookRefundController::class,'bookDetails']);
      Route::get('/book_stock_pdf', [BookstockController::class,'bookStockPdf']);
      Route::get('/book_issue_pdf', [BookIssueController::class,'bookIssuePdf']);
      Route::get('/book_no_return_pdf', [NoReturnBookController::class,'bookNoReturnPdf']);
      Route::get('/generate-pdf', [BookRefundController::class,'bookRefundPdf']);
      Route::get('scarddetails/{id}', [LibraryCardController::class, 'scarddetails'])->name('scarddetails');
      Route::get('classInfo/{id}/{depart_id}', [LibraryCardController::class,'classInfo']);
      Route::post('sessionInfo', [LibraryCardController::class,'sessionInfo']);
      Route::post('studentInfo', [LibraryCardController::class,'studentInfo']);
      Route::resource('sentinternal_mails', InternalMailController::class);
      Route::get('inboxinternal_mails', [InternalMailController::class, 'inbox']);
      Route::get('change_status/{id}', [InternalMailController::class, 'status']);
      Route::get('sentmaildetails/{id}', [InternalMailController::class, 'sentmaildetails']);
      Route::resource('exam_attendence', ExamAttendenceController::class);
    
      Route::resource('exam-buldingname', BuldingNameController::class);
      Route::resource('exam-room_no', RoomNoController::class);
      Route::resource('exam_setupplan', ExamsetupController::class);
      Route::get('exam_Info/{exam_id}',[ExamsetupController::class, 'ExamInformation'] );
      Route::get('departInfo/{depart_id}',[ExamsetupController::class, 'DepartInformation'] );
      Route::post('exam_setups_duty/export-pdf',[ExamsetupController::class, 'examSetupExportToPDF'] );
      Route::POST('examteachersearch/{id}', [ExamsetupController::class, 'teachersearch']);
      Route::resource('seat_card', ExamSeatcardController::class);
      Route::resource('examdutyroaster', ExamDutyRoasterController::class);
      Route::post('sendsms/{userId}', [ExamDutyRoasterController::class, 'sms_send']);
      Route::get('duty_examinfo/{id}', [ExamDutyRoasterController::class, 'dutyExaminfo']);
      Route::post('duty_roaster/sms_send', [ExamDutyRoasterController::class, 'dutyRoasterSmsSend']);
      Route::post('duty_roaster/all_sms_send', [ExamDutyRoasterController::class, 'dutyRoasterAllSmsSend']);
      Route::post('duty_roster/export-pdf',[ExamDutyRoasterController::class, 'DutyRosterExportToPDF'] );
      Route::resource('master-duty-roaster', ExamMasterDutyRosterController::class);
      Route::get('teacherInfo/{teacher_name}',[ExamMasterDutyRosterController::class, 'teacherInfo'] );
      Route::post('master_duty_roster/export-pdf',[ExamMasterDutyRosterEditableController::class, 'masterDutyRosterExportToPDF'] );
      Route::get('exam_name_editable/{title}', [ExamMasterDutyRosterEditableController::class, 'ExamMasterEditData'])
      ->name('exam_name_editable');
      Route::post('exam_master_duty_roster_editable', [ExamMasterDutyRosterEditableController::class, 'ExamMasterEditDataAction'])
      ->name('exam_master_duty_roster_editable');
      Route::resource('room-wise-master-duty', ExamRoomwiseMasterDutyController::class);
      Route::get('exam_id/{id}',[ExamRoomwiseMasterDutyController::class, 'ExamData'] );
      Route::get('exam_date/{date}/{examData}',[ExamRoomwiseMasterDutyController::class, 'ExamDateInfo'] );
      Route::get('teacherMasterInfo/{teacher_masterid}',[ExamRoomwiseMasterDutyController::class, 'teacherMasterInfo'] );
      Route::get('building_id/{id}',[ExamRoomwiseMasterDutyController::class, 'BuildingData'] );
      Route::post('exam_roomwise/export-pdf',[ExamRoomwiseEditableController::class, 'examRoomWiseExportToPDF'] );
      Route::get('exam_roomwise_editable/{title}', [ExamRoomwiseEditableController::class, 'ExamRoomwiseEditData'])
      ->name('exam_roomwise_editable');
      Route::post('exam_m_editable', [ExamRoomwiseEditableController::class, 'ExamRoomWiseEditDataAction'])
      ->name('exam_m_editable');
      Route::get('duty-roaster-single/{id}', [ExamDutyRoasterController::class,'dutyroatersingle']);
      Route::resource('exam_glance_seat_plan', GlanceSeatPlanController::class);
      Route::resource('examroutine', ExamRoutineController::class);
      Route::post('exam-routine-view', [ExamRoutineController::class,'examRoutineView']);
      Route::get('exam-routine-pdf',[ExamRoutineController::class,'examroutinePdf']);
      Route::resource('routinetime', RoutineTimeController::class);
 
      Route::resource('exam_seatplan', SeatPlanController::class);
      Route::post('department/exam_seatplan', [SeatPlanController::class, 'departExamShowSeatPlan']);
      Route::post('department/exam_seatplan/delete', [SeatPlanController::class, 'departExamSeatPlanDelete']);
      Route::post('department/exam_seat_Card', [SeatPlanController::class, 'departExamSeatCard']);
      Route::get('departmetn_id/{id}', [SeatPlanController::class,'departId']);
      Route::get('exam_routin/{id}', [SeatPlanController::class,'examRoutinData']);
      Route::get('class_id/{id}/{depart_id}', [SeatPlanController::class,'classId']);
      Route::post('session_data',[SeatPlanController::class, 'sessionData'] );
      //  Route::get('session_data/{id}', [SeatPlanController::class,'sessionData']);
      Route::resource('dranalysis', DRAnalysisController::class);
      Route::get('druploadUsers', [DRAnalysisController::class,'export']);
      Route::post('import', [DRAnalysisController::class,'import']);
      Route::post('/delete-data', [DRAnalysisController::class, 'deleteData'])->name('delete-data');
      Route::get('show_exam_seatplan/{room_num}',[SeatPlanController::class,'showSeatPlan']);
 
      
      Route::resource('dr_exam_routine', ExamDrRoutineController::class);
      Route::resource('drexamseatplan', DrExamSeatplanController::class);
      Route::resource('dr_exam_seat_list', ExamDrGlanceSeatListController::class);
      Route::get('dr_examName_Info/{id}', [ExamDrGlanceSeatListController::class,'drExamNameData']);
      Route::post('dr_glance_exam_list', [ExamDrGlanceSeatListController::class, 'drGlanceExamList']);
 
      Route::post('exam_seat_Card', [DrExamSeatplanController::class, 'examSeatCard']);
      Route::get('dr_exam_routine_info/{id}', [DrExamSeatplanController::class,'drExamRoutinData']);
      Route::post('exam_seatplan_show', [DrExamSeatplanController::class, 'examShowSeatPlan']);
      Route::post('exam_seatplan/delete', [DrExamSeatplanController::class, 'examSeatPlanDelete']);
      Route::get('dr_examinfo/{examdate_id}/{examinfo}', [DrExamSeatplanController::class,'drExamInfo']);
      Route::get('dr_collegeinfo/{college_name}', [DrExamSeatplanController::class,'drCollegeInfo']);
      Route::get('dr_subject/{subject}', [DrExamSeatplanController::class,'drSubject']);
      Route::get('dr_subjectinfo/{subject_name}/{collegeName}/{type}', [DrExamSeatplanController::class,'drSubjectInfo']);
      Route::get('dr_examinfo_secound/{examdate_id}/{examinfo}', [DrExamSeatplanController::class,'drExamInfoSecound']);
      Route::get('dr_collegeinfo_secound/{college_name}', [DrExamSeatplanController::class,'drCollegeInfoSecound']);
      Route::get('dr_subjectsecound/{subject}', [DrExamSeatplanController::class,'drSubjectSecound']);
      Route::get('dr_subjectinfoSecound/{subject_name}/{collegeName}/{type}', [DrExamSeatplanController::class,'drSubjectInfoSecound']);
      Route::get('dr_subjectthird/{subject}', [DrExamSeatplanController::class,'drSubjectThird']);
      Route::get('dr_examinfo_third/{examdate_id}/{examinfo}', [DrExamSeatplanController::class,'drExamInfoThird']);
      Route::get('dr_collegeinfo_third/{college_name}', [DrExamSeatplanController::class,'drCollegeInfoThird']);
      Route::get('dr_subjectinfoThird/{subject_name}/{collegeName}/{type}', [DrExamSeatplanController::class,'drSubjectInfoThird']);
      Route::resource('sportsteacherlist', SportsTeacherController::class);
      Route::resource('schampionslist', ChampionController::class);
      Route::resource('snoticelist', SNoticeController::class);
      Route::resource('journal-of-saadat', JournalOfSaadatController::class);
      Route::resource('college-magazine', JournalOfMagaginController::class);
      Route::resource('other-publication', OtherPublicationController::class);
      Route::resource('artsdepartment', ArtsdepartmentController::class);
      Route::resource('coteacherlist', CocurricularteacherController::class);
      Route::resource('cocurricularnotice', CocurricularNoticeController::class);
      Route::resource('cocurricularmanage', CoCurricularManageController::class);
      Route::post('/viceprincipaledit', [AdministrationController::class, 'viceprincipaledit'])->name('viceprincipaledit');
      Route::get('/redirect', [HomeController::class, 'redirect'])->name('redirect');
      Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
      Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
      Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
      Route::get('/principanladmin', [HomeController::class, 'principanladmin'])->name('principanladmin');
  
      Route::resource('bus_terminal', BusTerminalController::class);
      Route::resource('bus_schedule', BusScheduleController::class);
      Route::get('viceprincipal-inboxinternal_mails', [ViceprincipalController::class, 'inbox']);
      Route::get('inbox-mail-delete/{id}', [ViceprincipalController::class, 'inboxDistory']);
      Route::get('viceprincipalsentinternal_mails', [ViceprincipalController::class, 'sent']);
      Route::get('sent-mail-delete/{id}', [ViceprincipalController::class, 'distroy']);
      Route::post('emailstore', [ViceprincipalController::class, 'emailstore']);
      Route::get('vicemaildetails/{id}', [ViceprincipalController::class, 'details']);
      Route::resource('subofsubmenu', SubofsubmenuController::class);
  
      Route::resource('seatallotment', SeatAllotmentController::class);
      Route::resource('hostel_notice_board', HostelNoticeBoardController::class);
      Route::resource('hostel-general-info', HostelGeneralInfoController::class);
      Route::resource('hostel-application-rules', HostelApplicationController::class);
      Route::resource('hostel-head-info', HostelHeadContactController::class);
      Route::resource('hostel-gallery', HostelGalleryController::class);
      Route::resource('degree-notice', DegreePhotoNoticeController::class);
      Route::resource('hostelidcard', HostelIdCardController::class);
      Route::resource('hostelidcardnote', HostelIdCardNoteController::class);
      Route::get('hostcarddetails/{id}', [HostelIdCardController::class, 'hostcarddetails'])->name('hostcarddetails');
      // Route::get('studentreceipt/{id}', [HostelIdCardController::class, 'studentreceipt'])->name('studentreceipt');
      Route::get('studentData/{id}', [HostelIdCardController::class, 'StudentData']);
      Route::post('hostel_card_export', [HostelIdCardController::class, 'hostelIdCardExport']);
      Route::resource('hostel_logosign', HostelLogoSignController::class);
      Route::resource('hostel-bulding-name', HostelBuldingNameController::class);
      Route::resource('hostel-floor-name', HostelFloorController::class);
      Route::resource('hostel-room-number', HostelRoomController::class);
      Route::resource('hostel-seat-list-view', HostelSeatViewListController::class);
      Route::get('/hostel_seat_list_pdf', [HostelSeatViewListController::class,'hostelSeatList']);
      Route::resource('hostel-student-list', HostelStudentController::class);
      Route::resource('student_recipt_note', StudentReceipNoteController::class);

      // Route::get('studentreceipt/{id}', [HostelStudentController::class, 'studentreceipt'])->name('studentreceipt');
      // Route::get('/hostel_student_list_pdf', [HostelStudentController::class,'hostelStudentList']);
      Route::get('/studentreceiptdow/{id}', [HostelStudentController::class,'hostelStudentReceipt']);
      Route::get('buldingInfo/{id}', [HostelRoomController::class,'FloorName']);
      Route::get('hostel_classInfo/{id}/{depart_id}', [SeatAllotmentController::class,'HostelClassInfo']);
      Route::post('hostel_sessionInfo', [SeatAllotmentController::class,'HostelSessionInfo']);
      Route::post('hostel_studentInfo', [SeatAllotmentController::class,'HostelStudentInfo']);
      Route::get('/hostel_seat_allotment_pdf', [SeatAllotmentController::class,'hostelStudentList']);
      Route::get('studentreceipt/{id}', [SeatAllotmentController::class, 'studentreceipt'])->name('studentreceipt');

      Route::get('studentName/{id}', [SeatAllotmentController::class,'studentName']);

      Route::get('buldingID/{id}', [SeatAllotmentController::class, 'BulidingID']);
      Route::get('roomID/{id}', [SeatAllotmentController::class, 'roomID']);
      Route::get('roomInfo/{id}', [SeatAllotmentController::class, 'roomInfo']);
      Route::post('update-hostel-status', [SeatAllotmentController::class, 'UpdateStatus']);
      Route::get('get-room-number', [SeatAllotmentController::class, 'getRoomNumber'])->name('getRoomNumber');
      Route::get('get-floor-name', [SeatAllotmentController::class, 'getfloorName'])->name('getfloorName');
      //Degree Student
      Route::resource('degree_background_image', DegreeBackgroundImageController::class);
      Route::resource('degree_history', DegreeHistroyController::class);
      Route::resource('degree-mission-vision', DegreeMissionVissionController::class);
      Route::resource('degree-headofdepartment', DegreeOfHeadController::class);
      Route::resource('degree-teacher', DegreeTeacherController::class);
      Route::resource('degree-teacher-honour-board', DegreeTeacherHonourBoardController::class);
      Route::resource('degree_staff', DegreeStaffController::class);
      Route::resource('degree_photo_galleries', DegreePhotoGalleryController::class);
      Route::resource('degree-syllabus', DegreeSyllabusController::class);
      Route::resource('degree-class', DegreeClassController::class);
      Route::resource('degree-course', DegreeCourseController::class);
      Route::resource('degree-course-fee', DegreeCourseFeeController::class);
      Route::get('degree_coursefee_session/{id}',[DegreeCourseFeeController::class, 'degreeFeeSession'] );
      Route::get('degreegetcoursefeesession', [DegreeCourseFeeController::class, 'degreeGetCourseFeeSession'])->name('degreegetcoursefeesession');
      Route::resource('degree-regular-fee', DegreeRegularFeeController::class);
      Route::resource('degree-irregular-form-fillup', DegreeIrregularFeeController::class);
      Route::resource('degree-irregular-nonform-fillup', DegreeIrregularNonFormFillupController::class);
      Route::resource('degree-improvement-fee', DegreeImprovementController::class);
      Route::resource('degree-conditional-fee', DegreeConditionalPromotedController::class);
      Route::resource('degree-fail-course-fee', DegreeFailCoursFeeController::class);
      

      Route::resource('degree-class_schedules', DegreeClassScheduleController::class);
      Route::resource('degree_logo_sign', DegreeLogoSignController::class);
      Route::resource('degree_idcard_note', DegreeStudentIdCardNoteController::class);
      Route::resource('degree-first-year-sudetnts', DegreeFirstYearStudentController::class);
      Route::post('degree_first_year_import', [DegreeFirstYearStudentController::class,'degreeFirstYearImport']);
      Route::post('degree_first_year_idcard', [DegreeFirstYearStudentController::class,'degreeFirstYearIDCard']);
      Route::get('degree_firstyear_idcard/{id}', [DegreeFirstYearStudentController::class, 'DegreeFirstCardDetails'])->name('degree_firstyear_idcard');
      Route::get('degree_firstyear_studycertificate/{id}', [DegreeFirstYearStudentController::class, 'degreeFirstYearStudyCertificate']);
      
      
      
      Route::get('degree_firstyear_editable/{session}', [DegreeFirstYearEditabelController::class, 'degreeEditData'])
      ->name('degree_firstyear_editable');
      Route::post('degreefirsttabledit/action', [DegreeFirstYearEditabelController::class, 'DegreeEditDataAction'])
      ->name('degreefirsttabledit.action');
      Route::resource('degree-secound-year-students', DegreeSecoundYearStudentController::class);
      Route::post('degree_scound_year_import', [DegreeSecoundYearStudentController::class,'degreesecoundYearImport']);
      Route::post('degree_second_year_idcard', [DegreeSecoundYearStudentController::class,'DegreeSecondYearIdcard']);
      Route::get('degree_secondyear_idcard/{id}', [DegreeSecoundYearStudentController::class, 'DegreeSecondCardDetails'])->name('degree_secondyear_idcard');
      Route::get('degree_secondyear_studycertificate/{id}', [DegreeSecoundYearStudentController::class, 'degreeSecondYearStudyCertificate']);
      
      Route::resource('degree-third-year-students', DegreeThirdYearStudentController::class);
      Route::post('degree_third_year_import', [DegreeThirdYearStudentController::class,'degreeThirdYearImport']);
      Route::post('degree_third_year_idcard', [DegreeThirdYearStudentController::class,'DegreeThirdYearIdcard']);
      Route::get('degree_thirdyear_idcard/{id}', [DegreeThirdYearStudentController::class, 'DegreeThirdCardDetails'])->name('degree_thirdyear_idcard');
      Route::get('degree_thirdyear_studycertificate/{id}', [DegreeThirdYearStudentController::class, 'degreeThirdYearStudyCertificate']);
      Route::get('degree_testimonial/{id}', [DegreeThirdYearStudentController::class, 'degreeTestimonial']);
      
      Route::post('degree_firstyear_student_promote', [DegreeStudentPromoteController::class, 'DegreeFirstYearStudentPromote']);
      Route::post('degree_secondyear_student_promote', [DegreeStudentPromoteController::class, 'DegreeSecondYearStudentPromote']);

      Route::resource('degree-fourth-year-students', DegreeFourthYearStudentController::class);
      Route::post('degree_fourth_year_import', [DegreeFourthYearStudentController::class,'degreeFourthYearImport']);

      //Degree First Year Student Result
      Route::resource('degree-first-year-result', DegreeResultFirstYearStudentController::class);
      Route::get('degree_first_year/{id}',[DegreeResultFirstYearStudentController::class, 'degreeFirstYear'] );
      Route::post('getUserbyDegreeFirst',[DegreeResultFirstYearStudentController::class, 'getUserbyDegreeFirst'] );
      Route::get('degree-first-year-marksheet/{registration_no}',[DegreeResultFirstYearStudentController::class, 'degreeFirstYearMarksheet'] );
      // Route::get('degree_firstyear_testimonial/{id}',[DegreeResultFirstYearStudentController::class, 'degreeFirstYearTestimonial'] );

      
      //Degree Secound Year Student Result
      Route::resource('degree-secound-year-result', DegreeResultSecoundYearStudentController::class);
      Route::get('degree_secound_year/{id}',[DegreeResultSecoundYearStudentController::class, 'degreeSecoundYear'] );
      Route::post('getUserbyDegreeSecound',[DegreeResultSecoundYearStudentController::class, 'getUserbyDegreeSecound'] );
      Route::get('degree-secound-year-marksheet/{registration_no}',[DegreeResultSecoundYearStudentController::class, 'degreeSecoundYearMarksheet'] );
      //Degree Third Year Student Result
      Route::resource('degree-third-year-result', DegreeResultThirdYearStudentController::class);
      Route::get('degree_third_year/{id}',[DegreeResultThirdYearStudentController::class, 'degreeThirdYear'] );
      Route::post('getUserbyDegreeThird',[DegreeResultThirdYearStudentController::class, 'getUserbyDegreeThird'] );
      Route::get('degree-third-year-marksheet/{registration_no}',[DegreeResultThirdYearStudentController::class, 'degreeThirdYearMarksheet'] );
      //Degree Third Year Student Result
      Route::resource('degree-fourth-year-result', DegreeResultFourthYearStudentController::class);
      Route::get('degree_fourth_year/{id}',[DegreeResultFourthYearStudentController::class, 'degreeFourthYear'] );
      Route::post('getUserbyDegreeFourth',[DegreeResultFourthYearStudentController::class, 'getUserbyDegreeFourth'] );
      Route::get('degree-fourth-year-marksheet/{registration_no}',[DegreeResultFourthYearStudentController::class, 'degreeFourthYearMarksheet'] );
      Route::get('degree-consolidated-result/{registration_no}',[DegreeConsolidatedResultFinalYearController::class, 'degree_consolidated_result'] );

      Route::post('degree-result-list/export-pdf',[DegreeMeritListController::class, 'DegreeMeritexportToPDF'] );
      Route::post('degree-secound-year-result-list/export-pdf',[DegreeMeritListController::class, 'DegreeSecoundMeritexportToPDF'] );
      Route::post('degree-third-year-result-list/export-pdf',[DegreeMeritListController::class, 'DegreeThirdMeritexportToPDF'] );
      Route::post('degree-fourth-year-result-list/export-pdf',[DegreeMeritListController::class, 'DegreeFourthMeritexportToPDF'] );

      //Degree 1st Year Incourse Marks
      Route::resource('degree-first-year-incourse-mark', DegreeInCourseMarksFirstYearController::class);
      Route::post('degreeincourseFirst',[DegreeInCourseMarksFirstYearController::class, 'degreeIncourseFirst'] );
      Route::post('degree-first-incourse-result/export-pdf',[DegreeInCourseMarksFirstYearController::class, 'degreeFirstYearExportToPDF'] );
      //Degree 2nd Year Incourse Marks
      Route::resource('degree-second-year-incourse-mark',DegreeInCourseMarksSecoundYearController::class);
      Route::post('degreeincourseSecound',[DegreeInCourseMarksSecoundYearController::class, 'degreeIncourseSecound'] );
      Route::post('degree-secound-incourse-result/export-pdf',[DegreeInCourseMarksSecoundYearController::class, 'degreeSecoundYearExportToPDF'] );
      //Degree 3rd Year Incourse Marks
      Route::resource('degree-third-year-incourse-mark',DegreeInCourseMarksThirdYearController::class);
      Route::post('degreeincourseThird',[DegreeInCourseMarksThirdYearController::class, 'degreeIncourseThird'] );
      Route::post('degree-third-incourse-result/export-pdf',[DegreeInCourseMarksThirdYearController::class, 'degreeThirdYearExportToPDF'] );
      //Degree 4th Year Incourse Marks
      Route::resource('degree-fourth-year-incourse-mark',DegreeInCourseMarksFourthYearController::class);
      Route::post('degreeincourseFourth',[DegreeInCourseMarksFourthYearController::class, 'degreeIncourseFourth'] );
      Route::post('degree-fourth-incourse-result/export-pdf',[DegreeInCourseMarksFourthYearController::class, 'degreeFourthYearExportToPDF'] );
     
      Route::get('degree_sentinternal_mails', [DegreeInternalMailController::class, 'degree_sent']);
      Route::post('degree_email_store', [DegreeInternalMailController::class, 'degreeemailStore']);
      Route::get('degree_maildetails/{id}', [DegreeInternalMailController::class, 'degreedetails']);
      Route::get('degree-sent-mail-delete/{id}', [DegreeInternalMailController::class,'distroy']);
      Route::get('degree_inboxinternal_mails', [DegreeInternalMailController::class,'degreeinbox']);
      Route::get('degreeemaildetails/{id}', [DegreeInternalMailController::class, 'degreedetails']);
      Route::get('degree-inbox-mail-delete/{id}', [DegreeInternalMailController::class,'degreeinboxdistroy']);
      Route::resource('degree-result',DegreeResultController::class);
});

require __DIR__.'/auth.php';
